# Generated by Django 4.2.7 on 2023-12-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'Usd'), ('CAD', 'Cad'), ('NGN', 'Ngn'), ('GBP', 'Gbp'), ('EUR', 'Eur'), ('AUD', 'Aud'), ('GHC', 'Ghc')], max_length=10),
        ),
    ]
