# Generated by Django 4.2.7 on 2023-12-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='account_number',
        ),
    ]
