# Generated by Django 4.2.7 on 2023-12-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profiles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
