# Generated by Django 4.2.7 on 2023-12-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profiles_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='profile_pics',
            field=models.ImageField(blank=True, upload_to='hahhaha'),
        ),
    ]
