# Generated by Django 4.2.7 on 2023-12-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profiles_id_verification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='id_verification',
            new_name='document_type',
        ),
        migrations.AddField(
            model_name='profiles',
            name='document',
            field=models.ImageField(blank=True, upload_to='documents'),
        ),
    ]
