# Generated by Django 4.2.7 on 2023-12-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_id_verification_profiles_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='doc_verified',
            field=models.BooleanField(default=False),
        ),
    ]
