version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres_database
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 8001:8001
    container_name: sms_app_container
    command: >
      /venv/bin/python manage.py makemigrations &&
      /venv/bin/python manage.py migrate &&
      /venv/bin/python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
