# Generated by Django 4.2.7 on 2024-01-03 10:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_currency'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransfer',
            name='user',
        ),
        migrations.AddField(
            model_name='wallettransfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wallettransfer',
            name='receiver_account_number',
            field=models.CharField(default=None, max_length=11, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AddField(
            model_name='wallettransfer',
            name='sender_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AddField(
            model_name='wallettransfer',
            name='time_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wallettransfer',
            name='transaction_reference',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
