# Generated by Django 4.2.7 on 2024-01-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_deposit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='trf_id',
            field=models.CharField(max_length=16, verbose_name='Transaction Reference ID'),
        ),
    ]
